wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
dataset:
  desc: null
  value: ATIS
optimizer:
  desc: null
  value: Adam
momentum:
  desc: null
  value: 0.9
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.38.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723300401
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      3:
      - 16
      - 23
      - 61
      4: 3.10.10
      5: 0.17.5
      6: 4.38.0
      8:
      - 5
      13: linux-x86_64
model_size:
  desc: null
  value: 109602204
trainable_size:
  desc: null
  value: 109602204
