wandb_version: 1

recLayer_type:
  desc: null
  value: GRU
dataset:
  desc: null
  value: PennTreeBank
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.1
optimizer:
  desc: null
  value: SGD
embedding_size:
  desc: null
  value: 300
hidden_size:
  desc: null
  value: 300
dropout_enabled:
  desc: null
  value: true
embedding_dropout:
  desc: null
  value: 0.1
hidden_dropout:
  desc: null
  value: 0.1
output_dropout:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723479506
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.10.10
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
